#' Claude Files API. Upload and manage uploaded files. Download
#' files generated by Claude.
#'
#' Use the beta Files API to upload files to and manage files in Claude.
#' This is currently experimental because the API is in beta and may change.
#'
#' Uploaded files can be used in chat prompts as ContentAnthropicFile objects
#' passed to `chat_anthropic()` with appropriate beta headers set. Claude
#' offers 100GB of file storage per organization, and maximum size per file is
#' 500MB. For more details, please refer to:
#' [the documentation](https://docs.claude.com/en/docs/build-with-claude/files)
#' @description
#' `r lifecycle::badge("experimental")`
#' `anthropic_upload_file()` uploads a file to Anthropic's Claude and returns
#' a `ContentAnthropicFile` object that can be passed to `chat_anthropic()`.
#' @inheritParams chat_anthropic
#' @param fpath Path to a file to upload.
#' @param file_id ID of the file to get information about, download, or delete.
#' @param beta_headers Beta headers to use for the request. Defaults to
#'   `files-api-2025-04-14`.
#' @param api_key Your Anthropic API key. If `NULL`, will use the value of
#'   the `ANTHROPIC_API_KEY` environment variable.
#' @returns An object representing the uploaded file(s). The structure of this
#'   object may change as the API evolves.
#' @export
#' @examples
#' \dontrun{
#' file <- anthropic_upload_file("path/to/file.pdf")
#' chat <- chat_anthropic(beta_headers = "files-api-2025-04-14")
#' chat$chat("Please summarize the document.", file)
#' }
#' @description
#' `anthropic_list_files()` lists all files uploaded to your Anthropic
#' organization.
#' @returns A list of files with their metadata.
#' @export
#' @examples
#' \dontrun{
#' files <- anthropic_list_files()
#' print(files)
#' }
#'
#' @description
#' `anthropic_get_fileinfo()` returns a ContentAnthropicFile object for the
#' given file ID.
#' @returns A `ContentAnthropicFile` object representing the file.
#' @export
#' @examples
#' \dontrun{
#' file_info <- anthropic_get_fileinfo("file_id")
#' print(file_info) # ContentAnthropicFile object
#' }
#'
#' @description
#' `anthropic_download_file()` downloads the file with the given ID.
#' @returns The content of the file as a raw vector.
#' @export
#' @examples
#' \dontrun{
#' file_content <- anthropic_download_file("file_id")
#' writeBin(file_content, "downloaded_file.pdf")
#' }
#' @description
#' `anthropic_delete_file()` deletes the file with the given ID.
#' @returns Invisibly returns `NULL`.
#' @export
#' @examples
#' \dontrun{
#' anthropic_delete_file("file_id")
#' }
#'
#' @description
#' `anthropic_upload_file_raw()` uploads a file to Anthropic's Claude and
#' returns the raw response from the API. This can be useful for debugging or
#' if you need access to additional metadata not included in the
#' `ContentAnthropicFile` object. Note that this function does not provide any
#' special handling for the uploaded file, such as determining the appropriate
#' `block_type` for use in chat prompts. You will need to handle that manually
#' based on the `mime_type` returned in the response. Also, this function does
#' not validate the response, so be sure to check for errors in the returned
#' object.
#' @returns The raw response from the API as a list.
#' @export
#' @examples
#' \dontrun{
#' raw_response <- anthropic_upload_file_raw("path/to/file.pdf")
#' print(raw_response) # Raw response from the API
#' }
#'

anthropic_upload_file <- function(
  fpath,
  base_url = "https://api.anthropic.com/v1/files",
  beta_headers = "files-api-2025-04-14",
  api_key = anthropic_key()
) {
  res <- anthropic_init(base_url, beta_headers, api_key)
  res <- req_body_multipart(
    res,
    file = curl::form_file(
      fpath,
      type = guess_mime_type(fpath)
    )
  )
  resp <- req_perform(res)

  if (resp$status_code != 200) {
    stop("File upload failed: ", resp$status_code, call. = FALSE)
  }

  anthropic_create_content(resp_body_json(resp))
}

anthropic_upload_file_raw <- function(
  fpath,
  base_url = "https://api.anthropic.com/v1/files",
  beta_headers = "files-api-2025-04-14",
  api_key = anthropic_key()
) {
  res <- anthropic_init(base_url, beta_headers, api_key)
  res <- req_body_multipart(
    res,
    file = curl::form_file(
      fpath,
      type = guess_mime_type(fpath)
    )
  )
  resp <- req_perform(res)

  if (resp$status_code != 200) {
    stop("File upload failed: ", resp$status_code, call. = FALSE)
  }

  resp_body_json(resp)
}

anthropic_init <- function(url, beta_headers, api_key) {
  res <- request(url)
  res <- req_headers(res, `anthropic-version` = "2023-06-01")
  res <- req_headers_redacted(res, `x-api-key` = api_key)
  res <- req_headers(res, `anthropic-beta` = beta_headers)
  res
}

anthropic_create_content <- function(response) {
  mime_type <- response$mime_type
  switch(
    mime_type,
    "application/pdf" = ContentAnthropicFile(
      file_id = response$id,
      block_type = "document"
    ),
    "text/plain" = ContentAnthropicFile(
      file_id = response$id,
      block_type = "document"
    ),
    "image/jpeg" = ContentAnthropicFile(
      file_id = response$id,
      block_type = "image"
    ),
    "image/png" = ContentAnthropicFile(
      file_id = response$id,
      block_type = "image"
    ),
    "image/gif" = ContentAnthropicFile(
      file_id = response$id,
      block_type = "image"
    ),
    "image/webp" = ContentAnthropicFile(
      file_id = response$id,
      block_type = "image"
    ),
    "text/csv" = ContentAnthropicFile(
      file_id = response$id,
      block_type = "container_upload"
    ),
    "application/json" = ContentAnthropicFile(
      file_id = response$id,
      block_type = "container_upload"
    ),
    "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" = ContentAnthropicFile(
      file_id = response$id,
      block_type = "container_upload"
    ),
    "application/vnd.ms-excel" = ContentAnthropicFile(
      file_id = response$id,
      block_type = "container_upload"
    ),
    "text/xml" = ContentAnthropicFile(
      file_id = response$id,
      block_type = "container_upload"
    ),
    "application/xml" = ContentAnthropicFile(
      file_id = response$id,
      block_type = "container_upload"
    )
  )
}

anthropic_list_files <- function(
  base_url = "https://api.anthropic.com/v1/files",
  api_key = anthropic_key(),
  beta_headers = "files-api-2025-04-14"
) {
  res <- anthropic_init(base_url, beta_headers, api_key)
  resp <- req_perform(res)

  if (resp$status_code != 200) {
    stop("Failed to list files: ", resp$status_code, call. = FALSE)
  }

  resp_body_json(resp)$data
}

anthropic_get_fileinfo <- function(
  file_id,
  base_url = "https://api.anthropic.com/v1/files",
  api_key = anthropic_key(),
  beta_headers = "files-api-2025-04-14"
) {
  url <- paste0(base_url, "/", file_id)
  res <- anthropic_init(url, beta_headers, api_key)
  resp <- req_perform(res)

  if (resp$status_code != 200) {
    stop("Failed to get file info: ", resp)
  }

  anthropic_create_content(resp_body_json(resp))
}

anthropic_download_file <- function(
  file_id,
  base_url = "https://api.anthropic.com/v1/files",
  api_key = anthropic_key(),
  beta_headers = "files-api-2025-04-14"
) {
  url <- paste0(base_url, "/", file_id, "/content")
  res <- anthropic_init(url, beta_headers, api_key)
  resp <- req_perform(res)

  if (resp$status_code != 200) {
    stop("Failed to download file: ", resp$status_code, call. = FALSE)
  }

  resp_body_string(resp)
}

anthropic_delete_file <- function(
  file_id,
  base_url = "https://api.anthropic.com/v1/files",
  api_key = anthropic_key(),
  beta_headers = "files-api-2025-04-14"
) {
  url <- paste0(base_url, "/", file_id)
  res <- anthropic_init(url, beta_headers, api_key)
  res <- req_method(res, "DELETE")
  resp <- req_perform(res)

  if (resp$status_code != 200) {
    stop("Failed to delete file: ", resp$status_code, call. = FALSE)
  }

  return(invisible())
}
