#' Upload files to Claude via Files API and manage uploaded files. Download
#' files generated by Claude.
#'
#' @description
#' `r lifecycle::badge("experimental")`
#'
#' Use the beta Files API to upload files to Claude. This is currently
#' experimental because the API is in beta and may change.
#'
#' Uploaded files can be used in chat prompts via the `files` argument to
#' `chat_anthropic()` with appropriate beta headers set. Claude offers 100GB
#'  of file storage per organization, and maximum size per file is 500MB. See
#' [the documentation](https://docs.claude.com/en/docs/build-with-claude/files)
#'  for more details.
#'
#' @inheritParams chat_anthropic
#' @param path Path to a file to upload.
#' @param file_id ID of the file to get information about, download, or delete.
#' @param beta_headers Beta headers to use for the request. Defaults to
#'   `files-api-2025-04-14`.
#' @param api_key Your Anthropic API key. If `NULL`, will use the value of
#'   the `ANTHROPIC_API_KEY` environment variable.
#'
#' @returns An object representing the uploaded file(s). The structure of this
#'   object may change as the API evolves.
#' @export
#' @examples
#' \dontrun{
#' file <- anthropic_upload_file("path/to/file.pdf")
#' chat <- chat_anthropic(beta_headers = "files-api-2025-04-14")
#' chat$chat("Please summarize the document.", file)
#'

anthropic_upload_file <- function(
  fpath,
  base_url = "https://api.anthropic.com/v1/files",
  beta_headers = "files-api-2025-04-14",
  api_key = anthropic_key()
) {
  res <- anthropic_init(base_url, beta_headers, api_key)
  res <- req_body_multipart(
    res,
    file = curl::form_file(
      fpath,
      type = guess_mime_type(fpath)
    )
  )
  resp <- req_perform(res)

  if (resp$status_code != 200) {
    stop("File upload failed: ", resp$status_code, call. = FALSE)
  }

  anthropic_create_content(resp_body_json(resp))
}

anthropic_upload_file_raw <- function(
  fpath,
  base_url = "https://api.anthropic.com/v1/files",
  beta_headers = "files-api-2025-04-14",
  api_key = anthropic_key()
) {
  res <- anthropic_init(base_url, beta_headers, api_key)
  res <- req_body_multipart(
    res,
    file = curl::form_file(
      fpath,
      type = guess_mime_type(fpath)
    )
  )
  resp <- req_perform(res)

  if (resp$status_code != 200) {
    stop("File upload failed: ", resp$status_code, call. = FALSE)
  }

  resp_body_json(resp)
}

anthropic_init <- function(url, beta_headers, api_key) {
  res <- request(url)
  res <- req_headers(res, `anthropic-version` = "2023-06-01")
  res <- req_headers_redacted(res, `x-api-key` = api_key)
  res <- req_headers(res, `anthropic-beta` = beta_headers)
  res
}

anthropic_create_content <- function(response) {
  mime_type <- response$mime_type
  switch(
    mime_type,
    "application/pdf" = ContentAnthropicFile(
      file_id = response$id,
      block_type = "document"
    ),
    "text/plain" = ContentAnthropicFile(
      file_id = response$id,
      block_type = "document"
    ),
    "image/jpeg" = ContentAnthropicFile(
      file_id = response$id,
      block_type = "image"
    ),
    "image/png" = ContentAnthropicFile(
      file_id = response$id,
      block_type = "image"
    ),
    "image/gif" = ContentAnthropicFile(
      file_id = response$id,
      block_type = "image"
    ),
    "image/webp" = ContentAnthropicFile(
      file_id = response$id,
      block_type = "image"
    ),
    "text/csv" = ContentAnthropicFile(
      file_id = response$id,
      block_type = "container_upload"
    ),
    "application/json" = ContentAnthropicFile(
      file_id = response$id,
      block_type = "container_upload"
    ),
    "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" = ContentAnthropicFile(
      file_id = response$id,
      block_type = "container_upload"
    ),
    "application/vnd.ms-excel" = ContentAnthropicFile(
      file_id = response$id,
      block_type = "container_upload"
    ),
    "text/xml" = ContentAnthropicFile(
      file_id = response$id,
      block_type = "container_upload"
    ),
    "application/xml" = ContentAnthropicFile(
      file_id = response$id,
      block_type = "container_upload"
    )
  )
}

anthropic_list_files <- function(
  base_url = "https://api.anthropic.com/v1/files",
  api_key = anthropic_key(),
  beta_headers = "files-api-2025-04-14"
) {
  res <- anthropic_init(base_url, beta_headers, api_key)
  resp <- req_perform(res)

  if (resp$status_code != 200) {
    stop("Failed to list files: ", resp$status_code, call. = FALSE)
  }

  resp_body_json(resp)$data
}

anthropic_get_fileinfo <- function(
  file_id,
  base_url = "https://api.anthropic.com/v1/files",
  api_key = anthropic_key(),
  beta_headers = "files-api-2025-04-14"
) {
  url <- paste0(base_url, "/", file_id)
  res <- anthropic_init(url, beta_headers, api_key)
  resp <- req_perform(res)

  if (resp$status_code != 200) {
    stop("Failed to get file info: ", resp)
  }

  anthropic_create_content(resp_body_json(resp))
}

anthropic_download_file <- function(
  file_id,
  base_url = "https://api.anthropic.com/v1/files",
  api_key = anthropic_key(),
  beta_headers = "files-api-2025-04-14"
) {
  url <- paste0(base_url, "/", file_id, "/content")
  res <- anthropic_init(url, beta_headers, api_key)
  resp <- req_perform(res)

  if (resp$status_code != 200) {
    stop("Failed to download file: ", resp$status_code, call. = FALSE)
  }

  resp_body_string(resp)
}

anthropic_delete_file <- function(
  file_id,
  base_url = "https://api.anthropic.com/v1/files",
  api_key = anthropic_key(),
  beta_headers = "files-api-2025-04-14"
) {
  url <- paste0(base_url, "/", file_id)
  res <- anthropic_init(url, beta_headers, api_key)
  res <- req_method(res, "DELETE")
  resp <- req_perform(res)

  if (resp$status_code != 200) {
    stop("Failed to delete file: ", resp$status_code, call. = FALSE)
  }

  return(invisible())
}
